---
# Source: go-demo-7/charts/go-demo-7-db/templates/deployment-standalone.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-7-db
  labels:
    app: go-demo-7-db
    chart: go-demo-7-db-5.3.0
    release: "go-demo-7"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: go-demo-7-db
      release: "go-demo-7"
  template:
    metadata:
      labels:
        app: go-demo-7-db
        release: "go-demo-7"
        chart: go-demo-7-db-5.3.0
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
      - name: go-demo-7-db
        image: docker.io/bitnami/mongodb:4.0.3
        imagePullPolicy: "Always"
        env:
        - name: MONGODB_SYSTEM_LOG_VERBOSITY
          value: "0"
        - name: MONGODB_DISABLE_SYSTEM_LOG
          value: "no"
        - name: MONGODB_ENABLE_IPV6
          value: "yes"
        ports:
        - name: mongodb
          containerPort: 27017
        livenessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - mongo
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:
        - name: data
          mountPath: /bitnami/mongodb
        resources:
          {}
          
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: go-demo-7-db